In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('test1_preprocessed.csv')

In [3]:
data_preprocessed.tail()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
695               22          1         2     0                          8  
696               24          0         1     2                          3  
697               25          1         0     0                          8  
698               25          1         0     0                          2  
699               25          0         1     1                          2

In [4]:
#ターゲットの作成
data_preprocessed['Absenteeism Time in Hours'].median()
absent_median = data_preprocessed['Absenteeism Time in Hours'].median()

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > absent_median, 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.tail()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
695               22          1         2     0                          8   
696               24          0         1     2                          3   
697               25          1         0     0                          8   
698               25          1         0     0                          2   
699               25          0         1     1                          2   

     Excessive Absenteeism  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0

In [8]:
#データの調整
targets.sum() / targets.shape[0]

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Daily Work Load Average', 'Distance to Work'], axis=1)

In [10]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [11]:
#入力データの作成
data_with_targets.shape

(700, 13)

In [12]:
data_with_targets.iloc[:, 0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 13 columns]

In [13]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 12 columns]

In [14]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [15]:
unscaled_inputs.tail()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1

In [16]:
#データの標準化
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [17]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [18]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [19]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [20]:
#データの分割
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=20)

In [22]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(560, 12) (140, 12) (560,) (140,)


In [23]:
#モデルの作成
from sklearn.linear_model import LogisticRegression

In [24]:
reg = LogisticRegression()

In [25]:
reg.fit(x_train, y_train)

LogisticRegression()

In [26]:
reg.score(x_train, y_train)

0.7875

In [27]:
#正確性の導出
model_outputs = reg.predict(x_train)

In [28]:
np.sum((model_outputs == y_train) / model_outputs.shape[0])

0.7875000000000001

In [29]:
#切片の係数
reg.intercept_

array([-0.22344697])

In [30]:
reg.coef_

array([[ 2.07095215,  0.33292048,  1.55705081,  1.32145506,  0.19123008,
        -0.07545189,  0.69676291, -0.19326311,  0.31463294, -0.12374437,
         0.3829579 , -0.33344598]])

In [31]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [32]:
feature_name = unscaled_inputs.columns.values

In [33]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     2.070952
1                 Reason_2     0.332920
2                 Reason_3     1.557051
3                 Reason_4     1.321455
4              Month Value     0.191230
5          Day of the Week    -0.075452
6   Transportation Expense     0.696763
7                      Age    -0.193263
8          Body Mass Index     0.314633
9                Education    -0.123744
10                Children     0.382958
11                    Pets    -0.333446

In [34]:
summary_table.index = summary_table.index + 1

In [35]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -0.223447
1                 Reason_1     2.070952
2                 Reason_2     0.332920
3                 Reason_3     1.557051
4                 Reason_4     1.321455
5              Month Value     0.191230
6          Day of the Week    -0.075452
7   Transportation Expense     0.696763
8                      Age    -0.193263
9          Body Mass Index     0.314633
10               Education    -0.123744
11                Children     0.382958
12                    Pets    -0.333446

In [36]:
#係数の解釈
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -0.223447    0.799757
1                 Reason_1     2.070952    7.932372
2                 Reason_2     0.332920    1.395036
3                 Reason_3     1.557051    4.744807
4                 Reason_4     1.321455    3.748872
5              Month Value     0.191230    1.210738
6          Day of the Week    -0.075452    0.927324
7   Transportation Expense     0.696763    2.007245
8                      Age    -0.193263    0.824265
9          Body Mass Index     0.314633    1.369756
10               Education    -0.123744    0.883606
11                Children     0.382958    1.466616
12                    Pets    -0.333446    0.716451

In [38]:
#モデルのテスト
reg.score(x_test, y_test)


0.7357142857142858

In [39]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.7292112 , 0.2707888 ],
       [0.59107546, 0.40892454],
       [0.37444203, 0.62555797],
       [0.80649727, 0.19350273],
       [0.05830564, 0.94169436],
       [0.29629234, 0.70370766],
       [0.29735148, 0.70264852],
       [0.08276525, 0.91723475],
       [0.80915141, 0.19084859],
       [0.75157106, 0.24842894],
       [0.45661375, 0.54338625],
       [0.16370588, 0.83629412],
       [0.04426489, 0.95573511],
       [0.73604421, 0.26395579],
       [0.23574747, 0.76425253],
       [0.56404296, 0.43595704],
       [0.52473177, 0.47526823],
       [0.54919564, 0.45080436],
       [0.38702664, 0.61297336],
       [0.02529081, 0.97470919],
       [0.70004686, 0.29995314],
       [0.79841302, 0.20158698],
       [0.3849204 , 0.6150796 ],
       [0.40933685, 0.59066315],
       [0.18757949, 0.81242051],
       [0.76341879, 0.23658121],
       [0.49143696, 0.50856304],
       [0.88864424, 0.11135576],
       [0.12910291, 0.87089709],
       [0.79007893, 0.20992107],
       [0.

In [40]:
predicted_proba[:, 1]

array([0.2707888 , 0.40892454, 0.62555797, 0.19350273, 0.94169436,
       0.70370766, 0.70264852, 0.91723475, 0.19084859, 0.24842894,
       0.54338625, 0.83629412, 0.95573511, 0.26395579, 0.76425253,
       0.43595704, 0.47526823, 0.45080436, 0.61297336, 0.97470919,
       0.29995314, 0.20158698, 0.6150796 , 0.59066315, 0.81242051,
       0.23658121, 0.50856304, 0.11135576, 0.87089709, 0.20992107,
       0.38111985, 0.7016376 , 0.71569546, 0.57032536, 0.20158698,
       0.53871616, 0.19942251, 0.81411459, 0.44049238, 0.62000196,
       0.21789227, 0.40749331, 0.20887579, 0.10398703, 0.84748515,
       0.65453718, 0.70620978, 0.28097702, 0.19688205, 0.17702934,
       0.58133326, 0.08191275, 0.6929639 , 0.28387987, 0.87258519,
       0.4862031 , 0.93363555, 0.23794954, 0.07993359, 0.08019832,
       0.7249735 , 0.6812266 , 0.3030594 , 0.85690393, 0.18220809,
       0.26937168, 0.01321695, 0.21620848, 0.80886277, 0.30850535,
       0.19942251, 0.06947939, 0.93119622, 0.45755518, 0.65379

In [41]:
#デプロイ
import pickle
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [42]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)